---
abstract: 'backend class of kv2json'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-KV2JSON
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::KV2JSON:
    file: lib/App/KV2JSON.pm
    version: '0.01'
requires:
  JSON::PP: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/Songmu/App-KV2JSON/issues
  homepage: https://github.com/Songmu/App-KV2JSON
  repository: git://github.com/Songmu/App-KV2JSON.git
version: '0.01'
x_authority: cpan:SONGMU
